<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>$(WarningsAsErrors);nullable</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Deveel.CSharpCC/Deveel.CSharpCC.csproj" />
  </ItemGroup>
</Project>
