<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Deveel.CSharpCC</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../csharpcc/csharpcc.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Target Name="GenerateParser" BeforeTargets="CoreCompile" DependsOnTargets="ResolveProjectReferences">
    <MSBuild Projects="../csharpcc/csharpcc.csproj" Targets="GetTargetPath" Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework)">
      <Output TaskParameter="TargetOutputs" ItemName="ParserGenerator" />
    </MSBuild>
    <PropertyGroup>
      <GeneratedParserDirectory>$(IntermediateOutputPath)GeneratedParser</GeneratedParserDirectory>
      <DotNetHost Condition="'$(DotNetHostPath)' != ''">$(DotNetHostPath)</DotNetHost>
      <DotNetHost Condition="'$(DotNetHost)' == ''">dotnet</DotNetHost>
    </PropertyGroup>
    <RemoveDir Directories="$(GeneratedParserDirectory)" />
    <MakeDir Directories="$(GeneratedParserDirectory)" />
    <Exec Command="&quot;$(DotNetHost)&quot; &quot;@(ParserGenerator)&quot; -OUTPUT_DIRECTORY=&quot;$(GeneratedParserDirectory)&quot; &quot;$(MSBuildProjectDirectory)/SimpleParser.cc&quot;" />
    <ItemGroup>
      <Compile Include="$(GeneratedParserDirectory)/*.cs" />
      <FileWrites Include="$(GeneratedParserDirectory)/*.cs" />
    </ItemGroup>
  </Target>
</Project>
